global:
  resolve_timeout: 5m

route:
  receiver: telegram

receivers:
  - name: telegram
    telegram_configs:
      - bot_token: #### "your telegram bot token"
        chat_id: #### your chat id
        message: |
          {{ range .Alerts }}
          Alert: {{ .Labels.alertname }}

          Severity: {{ .Labels.severity }}
          Summary: {{ .Annotations.summary }}
          {{ end }}